server:
  address: 0.0.0.0
  port: 8080

#資料庫連線設定
spring:  
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.23.105:1433;database=chufa;trustServerCertificate=true
    username: sa
    password: P@ssw0rd
  mvc:
    converters:
      preferred-json-mapper: jackson
    static-path-pattern: /static/**
  mail:
    host: smtp.gmail.com
    port: 587
    username: "fafarere1104@gmail.com"  # 替換成你的 Gmail 帳號
    password: "azmm feqw xhtj ffef"  # 使用 Google 應用程式密碼
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379

  #Hibernate/JPA的相關設定
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#thymeleaf
  thymeleaf:
    enabled: true
    encoding: UTF-8
    mode: HTML
    cache: false
    prefix: classpath:/templates
    suffix: .html

#i18n
  messages:
    basename: messages
    encoding: UTF-8

jwt:
  token:
    expire: 10000

#line login
line:
  login:
    channel-id: "2006733552"
    channel-secret: "2e094b815ed92a5e16cb5938e9576102"
    callback-url: "http://192.168.23.105:6173/ajax/secure/callback/api/auth/line-login"

